title: RC-Dental Odontologia
description: "En nuestro consultorio odontológico, ubicado en Medellín,
  Laureles-Estadio, combinamos más de 12 años de experiencia con tecnología de
  vanguardia para ofrecer tratamientos dentales personalizados de alta calidad.
  Especializados en limpieza dental, ortodoncia, implantología y estética
  dental, garantizamos atención integral para tu salud bucal. Nuestro equipo de
  odontólogos altamente calificado brinda un ambiente cálido y seguro,
  escuchando y valorando a cada paciente. Ya sea para un chequeo, tratamiento
  del dolor dental o diseño de sonrisa, logramos resultados excepcionales.
  ¡Visítanos en el Edificio San Pablo, Cl. 49B #64B-54 Oficina 202 o agenda tu
  cita hoy mismo!"
baseurl: /RC-Dental
url: https://github.com/InvertedCode/RC-Dental
plugins:
  - jekyll-seo-tag
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
include:
  - assets
  - src